<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $studentForm \Zend\Form\Form */

$this->headTitle('Register student');

$this->headLink()->appendStylesheet(
    'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.1/css/bootstrap-datepicker3.standalone.min.css'
);
$this->inlineScript()->appendFile(
    'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.1/js/bootstrap-datepicker.min.js'
);
$this->inlineScript()->appendFile(
    $this->basePath('page/boostrap-datepicker.default.js')
);
$this->inlineScript()->appendFile(
    $this->basePath('page/autorun-boostrap-propover.js')
);
$this->inlineScript()->appendFile(
    $this->basePath('page/profile.form.js')
);
?>

<?php
$studentForm = $this->studentForm;
$studentForm->setAttribute('action', $this->url('student/add'));
$studentForm->prepare();
?>
<div class="container theme-showcase">
    <?= $this->form($studentForm); ?>
</div>
